"""update classes schema

Revision ID: 81dd1ee89594
Revises: e771f1c73ab5
Create Date: 2026-09-09 11:08:48.846021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81dd1ee89594'
down_revision: Union[str, Sequence[str], None] = 'e771f1c73ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('user_course_id', sa.UUID(), nullable=False))
    op.add_column('classes', sa.Column('class_index', sa.Integer(), nullable=False))
    op.add_column('classes', sa.Column('academic_year', sa.Integer(), nullable=False))
    op.add_column('classes', sa.Column('term', sa.Enum('ODD', 'EVEN', 'ODD_SHORT', 'EVEN_SHORT', name='term', native_enum=False, length=20), nullable=False))
    op.add_column('classes', sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='classstatus', native_enum=False, length=20), nullable=False))
    op.add_column('classes', sa.Column('schedule_day', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('schedule_start_time', sa.Time(), nullable=True))
    op.add_column('classes', sa.Column('schedule_end_time', sa.Time(), nullable=True))
    op.add_column('classes', sa.Column('room', sa.String(), nullable=True))
    op.create_index('ix_classes_user_course_id_class_index_unique_active', 'classes', ['user_course_id', 'class_index'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_foreign_key(None, 'classes', 'user_courses', ['user_course_id'], ['id'])
    op.drop_column('classes', 'semester')
    op.drop_column('classes', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('semester', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_index('ix_classes_user_course_id_class_index_unique_active', table_name='classes', postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('classes', 'room')
    op.drop_column('classes', 'schedule_end_time')
    op.drop_column('classes', 'schedule_start_time')
    op.drop_column('classes', 'schedule_day')
    op.drop_column('classes', 'status')
    op.drop_column('classes', 'term')
    op.drop_column('classes', 'academic_year')
    op.drop_column('classes', 'class_index')
    op.drop_column('classes', 'user_course_id')
    # ### end Alembic commands ###
