"""partial unique index on courses code

Revision ID: e2a798481294
Revises: ee7bc50de2ba
Create Date: 2026-09-04 05:39:44.999567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a798481294'
down_revision: Union[str, Sequence[str], None] = 'ee7bc50de2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_code_key'), 'courses', type_='unique')
    op.create_index('ix_courses_code_unique_active', 'courses', ['code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_code_unique_active', table_name='courses', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('courses_code_key'), 'courses', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
