"""add credits, category, delivery_type to courses

Revision ID: ee7bc50de2ba
Revises: 5b49fb429cd6
Create Date: 2026-09-04 03:09:33.770330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7bc50de2ba'
down_revision: Union[str, Sequence[str], None] = '5b49fb429cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('credits', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('category', sa.Enum('MW', 'MPP', 'MPI', 'MPK', 'MBKM', name='coursecategory', native_enum=False, length=10), nullable=False))
    op.add_column('courses', sa.Column('delivery_type', sa.Enum('THEORETICAL', 'PRACTICUM', 'WORKSHOP', name='coursedeliverytype', native_enum=False, length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'delivery_type')
    op.drop_column('courses', 'category')
    op.drop_column('courses', 'credits')
    # ### end Alembic commands ###
